### ISSUE TITLE
Remove top level node in the Contents section on type pages

### ISSUE THREAD

**Issue by danroth27** [danroth27/DNDocsWeb#12]
I like the Contents section at the top of each type page. It give you an easy way to navigate around the separate sections in a page. The top node in the contents, however, seems unnecessary as it points to the page itself. So instead of this:

![contents with two layers](https://cloud.githubusercontent.com/assets/1874516/7290974/4db20728-e93d-11e4-887e-85ddb3ead7d0.png)

Can we just have one layer like this?:

![contents with one layer](https://cloud.githubusercontent.com/assets/1874516/7290976/50b31d0e-e93d-11e4-96c5-a7d645340989.png)

**Comment by ericholscher** [comment]
Fixed in the newest build.
