### ISSUE TITLE
Nest syntax examples for members under the member

### ISSUE THREAD

**Issue by danroth27** [danroth27/DNDocsWeb#21]
Currently the syntax examples for members occupy the full width of the main content view. Is there a way to nest the syntax examples under each member so that the member list is easier to visually parse?

For example http://dndocsweb.azurewebsites.net/autoapi/Microsoft/CodeAnalysis/options/Option%601/index.html#property:

![member syntax too wide](https://cloud.githubusercontent.com/assets/1874516/7291393/b9778b5c-e944-11e4-8e00-6b77433498b1.png)

The syntax examples currently dominate the view and look too wide.

**Comment by ericholscher** [comment]
Believe our theme fixes this: 

![28_lz3dvlmmxnokzylvdulaj-ptx0gf29q51b34ugoq](https://cloud.githubusercontent.com/assets/25510/7327086/3b2cfc32-ea7f-11e4-8e6f-86b703e1c565.png)
