### ISSUE TITLE
yml everywhere instead of links

### ISSUE THREAD

**Issue by moozzyk** [danroth27/DNDocsWeb#22]
http://dndocsweb.azurewebsites.net/v2/autoapi/Microsoft/CodeAnalysis/CodeActions/index.html

class CodeAction An action produced by a [Microsoft.CodeAnalysis.CodeFixes.CodeFixProvider](Microsoft.CodeAnalysis.CodeFixes.CodeFixProvider.yml) or a [Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringProvider](Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringProvider.yml).

**Comment by agjohnson** [comment]
This sample project used markdown in documentation, we aren't targeting support for markdown here yet.

**Comment by agjohnson** [comment]
Closed this for now, tracking markdown support on #14
